jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Get actor email address
        id: user_email
        run: |
          EMAIL=$(gh api user/emails/verified --jq '.[0].email')
          echo "email=$EMAIL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send mail to user
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com # 或 smtp.163.com、smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Action 通知
          body: 您好，这是自动发送的邮件
          to: ${{ steps.user_email.outputs.email }}
          from: GitHub Actions
